### PR TITLE
#TP-18 ft:(simulate) bus motion integration 

### PR DESCRIPTION
**Pull request by sezeranoJchrisostome**
## What this PR Do?

`This  allows the driver to  interact with bus movement through the system`

### **Task to be completed **

- [x] The driver should be able to command the bus to start, move and stop.
- [x] TThe driver should be able to command the bus to speed up and slow down.
- [x] The driver should be able to update bus info on bus stops. e.g. number of passengers alighted and boarded.
- [x] The users should be able to view the bus movement in real-time.
- [x] Appropriate error messages are displayed on unsuccessful attempts.

WIP #TP-18

## Testing Repo

**Clone the repo**
then navigate to **ft-simulate-bus-motion-TP-14** branch

**Installation of dependencies.**
```
npm i
```
**Run development**
```
npm run dev
```

## Trello
[Card](https://trello.com/c/vtCZF0um/18-simulate-the-bus-motion)

## Screenshoot

localhost_8080_(iPhone 6_7_8) (4)

localhost_8080_(iPhone 6_7_8) (1)

localhost_8080_(iPhone 6_7_8)

localhost_8080_(iPhone 6_7_8) (2)

localhost_8080_(iPhone 6_7_8) (3)

localhost_8080_(iPhone 6_7_8) (5)

### CODE REVIEW

**Review by renepromesse — CHANGES_REQUESTED** [review]
Good work @sezeranoJchrisostome ,
please rebase and add the screenshots

**Comment by sezeranoJchrisostome** [comment]
> Good work @sezeranoJchrisostome , please rebase and add the screenshots

**Review by renepromesse — COMMENTED** [review]
@sezeranoJchrisostome could you improve these tests?

**Review by renepromesse — APPROVED** [review]
Good job

**Pull request merged**
