### PR TITLE
Update driver or operator profile #TP-39

### PR DESCRIPTION
**Pull request by sezeranoJchrisostome**
### What does this PR do?

- This pr will allow the operator and drivers to update their profile and reveal their information publically 

### How can it manually be tested?

- After cloning this repo,
- Navigate to fe-update-profile-TP-39 branch
- you need to run `npm install` just in case you don't have new dependence
- run `npm run dev` on your local terminal 
- Click on your profile picture in the header and then
- you will be able to update your profile and also 

### Related Trello board stories

- https://trello.com/c/v1qBH95w/39-update-profile

### Screenshoot

Screenshot 2022-03-07 124112

### CODE REVIEW

**Review by renepromesse — DISMISSED** [review]
Hey, @sezeranoJchrisostome and @Delyc  please follow git workflow when creating your PRs.
refer to the document shared on our slack channel.
- what does this PR do?
- how to test it? etc...
- fix the tests and make sure it is passing

**Review by renepromesse — COMMENTED** [review]
Hey @sezeranoJchrisostome, please fix this tests

**Comment by sezeranoJchrisostome** [comment]
> Hey @sezeranoJchrisostome, please fix this tests

It has been improved

**Comment by sezeranoJchrisostome** [comment]
> Hey, @sezeranoJchrisostome and @Delyc please follow git workflow when creating your PRs. refer to the document shared on our slack channel.
> 
> * what does this PR do?
> * how to test it? etc...
> * fix the tests and make sure it is passing

Also this is fixed

**Review by renepromesse — APPROVED** [review]
Greaat work @sezeranoJchrisostome

**Pull request merged**
